name: Scheduled Data Loader

# Trigger the workflow on a schedule
on:
  schedule:
    - cron: "0 * * * *" # Runs at the start of every hour (UTC time)

jobs:
  run-data-loader:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Specify your Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the data loader script
      - name: Run data loader script
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          python your_data_loader_script.py

      # Optional Step 5: Commit and push updated data (if needed)
      - name: Commit and Push Updated Data
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update data from scheduled data loader"
          git push origin main
