name: Deploy

on:
  # Run this workflow whenever a new commit is pushed to main.
  push: {branches: [main]}
  # Run this workflow once per hour
  schedule: [{cron: "0 * * * *"}]
  # Run this workflow when triggered manually in GitHub's UI.
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Set up Python for data loaders
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      
      # Install Node.js dependencies
      - run: npm ci
      
      # Build the site (data loaders will run automatically)
      - run: npm run build
        env:
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      
      # Deploy to Github Pages
      - name: Deploy to Github pages
        run: npm run deploy -- --message "$(git log -1 --pretty=%s)"
        env:
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
